spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chatbot_db
    username: postgres
    password: 0000
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true